# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - master
    tags: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        source-url: https://nuget.pkg.github.com/SephDB/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: dotnet restore
    - run: dotnet build
    - name: Create the package
      run: dotnet pack --configuration Release
    - name: Publish the package to GPR
      run: dotnet nuget push Runtime/bin/Release/*.nupkg
